### ISSUE TITLE
Export metrics from systemd

### ISSUE THREAD

**Issue by arianvp** [themalkolm/systemd_exporter#2]
Systemd keeps all kinds of Cgroup metrics for you.

I exposed those in this PR in `node_exporter` https://github.com/prometheus/node_exporter/pull/709 but they found it too much of a scope-creep.  Would you accept a PR to move this behaviour to this repository? It seems like a good fit.

**Comment by themalkolm** [comment]
Sure, we can't take a look.

**Comment by themalkolm** [comment]
I did this project for the same reason :)

**Comment by arianvp** [comment]
Ok great! I'll rebase the PR on this repo instead then :)

**Comment by themalkolm** [comment]
Try to fit into the codebase and protect with feature flag. If you tell me how to reliably test it - will also help.

**Comment by arianvp** [comment]
Ok great. How do I update the `vendor` dir easily? I perhaps need a new version of `go-systemd`

**Comment by themalkolm** [comment]
Can't check but something like this

```
$ make install-gb
$ export PATH=${PATH}:$(pwd)/vendor/bin
$ gb vendor update github.com/coreos/go-systemd
```

Note that go-systemd version must match `github.com/godbus/dbus` version etc.

**Comment by themalkolm** [comment]
I see that author decided to continue with an attempt to merge changes to node_exporter instead. Closing.
