### ISSUE TITLE
Uptime in milliseconds isn't actually milliseconds

### ISSUE THREAD

**Issue by langesven** [themalkolm/systemd_exporter#3]
We started using this exporter because we needed the uptime of certain systemd services for monitoring.
As I was writing alert rules I noticed that the metric that claims to show the uptime in milliseconds is showing it in microseconds.
https://github.com/themalkolm/systemd_exporter/blob/bc216d47209d99195e5b353c506d6cf53c22ab19/src/cmd/systemd_exporter/collector.go#L117 
Nanoseconds / 1000 yields microseconds, not milliseconds.
To keep backward compatibility the solution would be to adjust the metric description and README, since the variable `ms` conveniently would pass for milliseconds and microseconds.
Or you could bump the major version and make it actually represent milliseconds, which would require people to adjust their dashboards / alerts for the changed dimension of the metric.

**Comment by themalkolm** [comment]
Oh, I don’t think I cared about absolute numbers much. Sure, we can fix this.

**Comment by themalkolm** [comment]
* Updated docs
* Added uptime_seconds (following recommendations in https://prometheus.io/docs/practices/naming/)

https://github.com/themalkolm/systemd_exporter/releases/tag/v2018.03.06

**Comment by themalkolm** [comment]
@langesven feel free to reopen if it doesn't work
